In [ ]:
import pandas as pd
import sys
import os

# Pega o caminho da pasta atual (notebooks) e volta um nível para a raiz do projeto
project_path = os.path.abspath(os.path.join(os.getcwd(), '..'))
# Adiciona a pasta raiz à lista de caminhos que o Python usa para procurar módulos
if project_path not in sys.path:
    sys.path.insert(0, project_path)

from src.data_processing import process_main_movie_data, create_genre_dataset

print("Módulos e funções importados com sucesso.")

Módulos e funções importados com sucesso.

In [ ]:
# Carrega o resultado do script get_data.py
caminho_do_arquivo = '../data/raw/tmdb_movies_raw.csv'
raw_movies_df = pd.read_csv(caminho_do_arquivo)

print(f"Dados brutos carregados com sucesso. Foram encontradas {len(raw_movies_df)} linhas.")
display(raw_movies_df.head())

Dados brutos carregados com sucesso. Foram encontradas 5431 linhas.

,ID do Filme,Nome do Filme,Gênero,Avaliação,Nº de Avaliações,Lançamento,Nacionalidade,Duração,Popularidade,Orçamento,Receita,Atores Principais
0,11,Guerra nas Estrelas,"Aventura, Ação, Ficção científica",8.205,21446,1977-05-25,United States of America,121,16.8045,11000000,775398007,"Mark Hamill, Harrison Ford, Carrie Fisher"
1,12,Procurando Nemo,"Animação, Família",7.817,19884,2003-05-30,United States of America,100,16.6090,94000000,940335536,"Albert Brooks, Ellen DeGeneres, Alexander Gould"
2,13,Forrest Gump: O Contador de Histórias,"Comédia, Drama, Romance",8.466,28586,1994-06-23,United States of America,142,20.4914,55000000,677387716,"Tom Hanks, Robin Wright, Gary Sinise"
3,14,Beleza Americana,Drama,8.005,12533,1999-09-15,United States of America,122,11.0890,15000000,356296601,"Kevin Spacey, Annette Bening, Thora Birch"
4,15,Cidadão Kane,"Mistério, Drama",8.000,5740,1941-04-17,United States of America,119,5.3089,839727,23218000,"Orson Welles, Joseph Cotten, Dorothy Comingore"

In [14]:
# Chama as funções que criamos para limpar, transformar e filtrar os dados
cleaned_movies_df = process_main_movie_data(raw_movies_df)
movies_by_genre_df = create_genre_dataset(cleaned_movies_df)

print(f"\nDataFrame principal, limpo e processado:")
display(cleaned_movies_df.head())

print(f"\nDataFrame de gêneros:")
display(movies_by_genre_df.head())

Processamento concluído. DataFrame final com 2488 filmes.
Criação do DataFrame de gêneros concluída.

DataFrame principal, limpo e processado:

,ID do Filme,Nome do Filme,Gênero,Avaliação,Nº de Avaliações,Lançamento,Nacionalidade,Duração,Popularidade,Orçamento,Receita,Atores Principais,Receita Líquida
10,496243,Parasita,"Comédia, Thriller, Drama",8.5,19433,2019-05-30,South Korea,132,23.9385,11363000,257591776,"Kang-ho Song, Sun-kyun Lee, Yeo-Jeong Cho",246228776
12,372058,Seu Nome,"Animação, Romance, Drama",8.5,11949,2016-08-26,Japan,106,14.0341,<NA>,358000000,"Ryunosuke Kamiki, 上白石萌音, 成田凌",<NA>
24,696374,O Inferno de Gabriel,"Romance, Drama",8.4,2430,2020-05-29,United States of America,120,2.0511,<NA>,<NA>,"Melanie Zanetti, Giulio Berruti, Kurt McKinney",<NA>
29,324857,Homem-Aranha: No Aranhaverso,"Animação, Ação, Aventura, Ficção científica",8.4,16403,2018-12-06,United States of America,117,19.6918,90000000,393602435,"Shameik Moore, Jake Johnson, Hailee Steinfeld",303602435
31,378064,A Voz do Silêncio,"Animação, Drama, Romance",8.4,4202,2016-09-17,Japan,130,9.6162,<NA>,30819442,"Miyu Irino, Saori Hayami, Aoi Yuki",<NA>

DataFrame de gêneros:

,ID do Filme,Nome do Filme,Gênero,Avaliação,Nº de Avaliações,Lançamento,Nacionalidade,Duração,Popularidade,Orçamento,Receita,Atores Principais,Receita Líquida
10,496243,Parasita,Comédia,8.5,19433,2019-05-30,South Korea,132,23.9385,11363000,257591776,"Kang-ho Song, Sun-kyun Lee, Yeo-Jeong Cho",246228776
10,496243,Parasita,Thriller,8.5,19433,2019-05-30,South Korea,132,23.9385,11363000,257591776,"Kang-ho Song, Sun-kyun Lee, Yeo-Jeong Cho",246228776
10,496243,Parasita,Drama,8.5,19433,2019-05-30,South Korea,132,23.9385,11363000,257591776,"Kang-ho Song, Sun-kyun Lee, Yeo-Jeong Cho",246228776
12,372058,Seu Nome,Animação,8.5,11949,2016-08-26,Japan,106,14.0341,<NA>,358000000,"Ryunosuke Kamiki, 上白石萌音, 成田凌",<NA>
12,372058,Seu Nome,Romance,8.5,11949,2016-08-26,Japan,106,14.0341,<NA>,358000000,"Ryunosuke Kamiki, 上白石萌音, 成田凌",<NA>

In [16]:
cleaned_movies_df.shape

(2488, 13)

In [17]:
import os # <-- Adicionamos este import para manipular pastas e arquivos

# Define os caminhos de saída na pasta 'processed'
output_path_analise = '../data/processed/filmes_analise_final.csv'
output_path_generos = '../data/processed/filmes_genero_final.csv'

# --- A CORREÇÃO MÁGICA ---
# Garante que o diretório de destino exista antes de tentar salvar
os.makedirs(os.path.dirname(output_path_analise), exist_ok=True)
# -------------------------

# Salva os arquivos
cleaned_movies_df.to_csv(output_path_analise, index=False, encoding='utf-8-sig')
movies_by_genre_df.to_csv(output_path_generos, index=False, encoding='utf-8-sig')

print(f"Arquivos finais salvos com sucesso na pasta 'data/processed/'!")
print(f"Tudo pronto para importar no Power BI.")

Arquivos finais salvos com sucesso na pasta 'data/processed/'!
Tudo pronto para importar no Power BI.

### Análise de Dados Faltantes: Orçamento e Receita

Após o tratamento inicial, observamos que as colunas `Orçamento` e `Receita` ainda contêm um número significativo de valores nulos. Aproximadamente **30% dos filmes** no nosso dataset final não possuem informações financeiras divulgadas.

**Decisão:** Para as análises financeiras (como Receita Líquida), esses filmes serão desconsiderados para não distorcer as médias e os totais. No entanto, eles serão mantidos para outras análises não financeiras, como popularidade por gênero ou avaliação.